### ISSUE TITLE
Add head ref as input

### ISSUE THREAD

**Issue by gagle** [dorny/paths-filter#79]
I would like to pass also the head ref as parameter. I have several workflows that listens to workflow_dispatch and repository_dispatch and I need to filter files by path given a head and base ref.

**Comment by dorny** [comment]
With `workflow_dispatch` you define the branch receiving the trigger. I'm not 100% sure but I would expect it should already work. Unless you need to have different head ref then the branch where workflow runs...

However to support `repository_dispatch` I will have to do some changes. I will look into it.

**Comment by dorny** [comment]
I got it working on branch `issue-79-add-head-ref-input`.
However I still have to do some tests before merging it to ensure it doesn't break anything else.

**Comment by gagle** [comment]
Thanks a lot. We will be using it at the Seat car manufacturer company 👍🏻 . I had to implement my own action based on yours. Used in a gitflow implementation using github actions.

**Comment by dorny** [comment]
So there is a chance I could get a discount when buying Seat car? 😄

Just joking, I'm happy that this action is useful for others.
I've just released new version with `ref` input parameter implemented so I'm closing the issue now.

**Comment by gagle** [comment]
I've seen that you know switched to 3 diff dots instead of 2. Why?

**Comment by dorny** [comment]
No, 3 diff dots had been used for a long time (see #33 ). Maybe you misinterpreted the changes?

Explanation:
- With 2 diff dots you get exact diff between two snapshots (commits).
- With 3 diff dots you see what has been changed on your (feature) branch since it diverged from your base branch

3 diff dots is what you see when you create a PR.
Otherwise diff would contain also changes on base unrelated to work on feature branch.
That's why this action is fetching more commits until it founds merge-base - the point where feature and base branch diverged.
I'm using 2 diff dots only in some cases - e.g. when you are comparing two commits on same branch after `push` event.

**Comment by gagle** [comment]
Thanks for the explanation. This action it's basically the piece that enables monorepos to build/lint/deploy only specific parts of the system. I would like to use it to build another actions that are based on path filtering. I've tried to `npm install` it but it's not in the npm registry. Do you think it would require a lot of effort to also convert it into a reusable npm lib?

**Comment by dorny** [comment]
Extracting functionality related to fetching into the npm package is quite an interesting idea. It should probably contain only parts using `git` commands and not depending on GitHub APIs. I can't give you any promises when it will be done, but I like the idea.
